### PR TITLE
Migrate to JUnit 5

### LINKED ISSUE #80: Migrate to JUnit 5

### PR DESCRIPTION
**Pull request by rshindo**
Close #80

### CODE REVIEW

**Comment by backpaper0** [comment]
If I add tests in the future, I would like to use JUnit 5.
But I don't want to migrate existing tests to JUnit 5.
Is there any reason why should be migrate or benefit?

**Comment by rshindo** [comment]
@backpaper0 
Thank you for your comment. I think there are some reasons to migrate to JUnit 5:

1. Spring Boot no longer contains JUnit 4 via junit-vintage-engine (2.4-). If we continue JUnit 4, we have to add junit-vintage-engine in each pom.xml. 
2. Indeed, it's reasonable to mix JUnit 5 tests with legacy tests **temporarily**. But two styles of tests require high maintenance costs. 

These motivations are not positive, but someone have to do someday 😉

**Comment by backpaper0** [comment]
@rshindo 
Thanks fo your reply!
I don't think two styles of tests are high maintenance costs.
More than that, I want to avoid the cost of review in this one pull request.

On the other hand, I would like to choose JUnit 5 style when I write new test.
so, I would like to make changes so that both styles tests work.

**Comment by rshindo** [comment]
@backpaper0 
I got that point. I close this pull request.
And I will use JUnit 5 in new tests.

**Comment by backpaper0** [comment]
@rshindo 
I modified pom.xml for using JUnit 5. #82 
New test can be written by JUnit 5 style.

**Pull request closed without merging**
